import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
      },
      sliderContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        marginVertical: 10,
      },
      sliderLabel: {
        fontSize: 16,
        fontWeight: 'bold',
      },
      mapContainer: {
        ...StyleSheet.absoluteFillObject,
      },
      mapImage: {
        width: '100%',
        height: '100%',
        resizeMode: 'cover',
      },
      contentContainer: {
        flex: 1,
        justifyContent: 'flex-end',
      },
      bottomAlignedContent: {
        justifyContent: 'flex-end',
        paddingBottom: 20,
      },
      navbar: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 15,
        height: 110,
        zIndex: 1000,
      },
      menuButton: {
        padding: 5,
      },
      appName: {
        fontSize: 18,
        fontWeight: 'bold',
        color: 'white',
      },
      placeholder: {
        width: 24,
      },
      settingsContainer: {
        backgroundColor: 'white',
        borderRadius: 10,
        padding: 15,
        marginHorizontal: 15,
        marginBottom: 20,
        shadowColor: "#000",
        shadowOffset: {
          width: 0,
          height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
      },
      settingItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 15,
      },
      settingTitleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
      },
      settingTitle: {
        marginLeft: 10,
      },
      settingIconContainer: {
        width: 30,
        height: 30,
        borderRadius: 8,
        backgroundColor: '#E5E5EA',
        justifyContent: 'center',
        alignItems: 'center',
      },
      trustedContactsButton: {
        backgroundColor: '#E5E5EA',
        padding: 10,
        borderRadius: 5,
        alignItems: 'center',
      },
      trustedContactsText: {
        color: '#007AFF',
      },
      actionButtonsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginHorizontal: 15,
        marginBottom: 20,
      },
      actionButton: {
        flex: 1,
        marginHorizontal: 5,
        height: 50,
        borderRadius: 5,
        overflow: 'visible', // Change this from 'hidden' to 'visible'
        shadowColor: "#000",
        shadowOffset: {
          width: 0,
          height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
      },
      gradientButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        height: '100%',
        borderWidth: 1,
        borderColor: 'white',
        borderRadius: 5,
        paddingHorizontal: 10,
      },
      actionButtonText: {
        color: 'white',
        fontWeight: 'bold',
        marginLeft: 8, // Adjusted for spacing between icon and text
      },
      iconContainer: {
        width: 30,
        height: 30,
        borderRadius: 15,
        borderWidth: 1,
        borderColor: 'white',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 5,
      },
      shareButton: {
        marginHorizontal: 15,
        marginBottom: 20,
        borderRadius: 5,
        overflow: 'visible', // Change this from 'hidden' to 'visible'
        height: 50,
        shadowColor: "#000",
        shadowOffset: {
          width: 0,
          height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
      },
      shareButtonGradient: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        height: '100%',
        borderWidth: 1,
        borderColor: 'white',
        borderRadius: 5,
        paddingHorizontal: 10,
      },
      shareButtonText: {
        color: 'white',
        fontWeight: 'bold',
        marginLeft: 8,
      },
      listeningContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginHorizontal: 15,
        marginBottom: 20,
        backgroundColor: 'rgba(255, 255, 255, 0.8)',
        borderRadius: 10,
        padding: 10,
        position: 'absolute',
        top: -60,
        left: 0,
        right: 0,
        zIndex: 1000,
        shadowColor: "#000",
        shadowOffset: {
          width: 0,
          height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
      },
      listeningDot: {
        width: 10,
        height: 10,
        borderRadius: 5,
        backgroundColor: 'red',
        marginRight: 10,
      },
      listeningText: {
        color: '#333',
      },
      activateContainer: {
        backgroundColor: 'white',
        borderRadius: 10,
        padding: 15,
        marginHorizontal: 15,
        marginBottom: 20,
        alignItems: 'center',
        shadowColor: "#000",
        shadowOffset: {
          width: 0,
          height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
      },
      activateText: {
        fontSize: 18,
        fontWeight: 'bold',
        marginBottom: 10,
        textAlign: 'center',
      },
      activateSwitch: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 10,
        paddingVertical: 10,
      },
      switch: {
        transform: [{ scaleX: 1.5 }, { scaleY: 1.5 }],
      },
      instructionText: {
        color: '#8E8E93',
        fontSize: 12,
        marginBottom: 5,
        textAlign: 'center',
      },
      poweredByAI: {
        color: '#8E8E93',
        fontSize: 10,
        position: 'absolute',
        bottom: 5,
        right: 10,
      },
      openMapsButton: {
        position: 'absolute',
        top: 120,
        right: 15,
        backgroundColor: 'white',
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: 5,
        zIndex: 1001,
        shadowColor: "#000",
        shadowOffset: {
          width: 0,
          height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
      },
      openMapsText: {
        color: '#007AFF',
      },
});